os:
  - linux
  # Disabled due to lack of OpenMP support in Travis' OSX environment
  # - osx

language: c

compiler:
  - gcc
  # No clang with OpenMP support until Ubuntu 16.04 (via libomp-dev)
  # - clang

install:
  - mkdir _dep_install
  # heartbeats-simple dependency
  - wget https://github.com/libheartbeats/heartbeats-simple/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - mkdir -p heartbeats-simple-master/_build
  - cd heartbeats-simple-master/_build
  - cmake -DCMAKE_INSTALL_PREFIX=../../_dep_install ..
  - cmake --build . --target install
  - cd ../..
  # energymon dependency (use default dummy implementation)
  - wget https://github.com/energymon/energymon/archive/master.zip
  - unzip master.zip
  - rm master.zip
  - mkdir -p energymon-master/_build
  - cd energymon-master/_build
  - cmake -DCMAKE_INSTALL_PREFIX=../../_dep_install ..
  - cmake --build . --target install
  - cd ../..

script:
  - mkdir _build
  - cd _build
  - PKG_CONFIG_PATH="../_dep_install/lib/pkgconfig" cmake ..
  - cmake --build .
  - ctest -VV
